{% set name = "pygalmesh" %}
{% set version = "0.10.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2db842cfd43aed9beb2c3a2dae6276206d16587131b6f068f6c5ba049b6af2f9

build:
  number: 2
  entry_points:
    - pygalmesh = pygalmesh._cli:cli

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - eigen
    - cgal-cpp >=5.0.0,<6
    - pybind11
    - mpfr
    - gmp  # [not win]
    - mpir  # [win]
  run:
    - python
    - meshio
    - importlib_metadata

test:
  imports:
    - pygalmesh
  requires:
    - pytest
    - pytest-codeblocks
    - numpy
  source_files:
    - tests
  commands:
    - pytest --codeblocks
    - pygalmesh volume-from-surface -h
    - pygalmesh remesh-surface -h
    - pygalmesh from-inr -h

about:
  home: https://github.com/nschloe/pygalmesh/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: A Python frontend to CGAL’s 3D mesh generators.
  description: |
    pygalmesh is a Python frontend to CGAL’s 3D mesh generation capabilities. pygalmesh makes it easy to create high-quality 3D volume meshes, periodic volume meshes, and surface meshes. 
  doc_url: https://github.com/nschloe/pygalmesh
  dev_url: https://github.com/nschloe/pygalmesh

extra:
  recipe-maintainers:
    - nschloe
    - flothesof
