{% set name = "pygalmesh" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c5d695647ff2ac7fa86f9a2539ce7dc8990a953a9cdedc8418fada8b6ddc2e7b

build:
  number: 0
  entry_points:
    - pygalmesh-volume-from-surface = pygalmesh._cli:volume_from_surface
    - pygalmesh-remesh-surface = pygalmesh._cli:remesh_surface
    - pygalmesh-from-inr = pygalmesh._cli:inr

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - eigen
    - cgal-cpp >=5.0.0,<6
    - pybind11
    - mpfr
    - gmp  # [not win]
    - mpir  # [win]
  run:
    - python
    - meshio
    - importlib_metadata

test:
  imports:
    - pygalmesh
  requires:
    - pytest
    - numpy
  source_files:
    - test
  commands:
    - pytest
    - pygalmesh-volume-from-surface -h
    - pygalmesh-remesh-surface -h
    - pygalmesh-from-inr -h

about:
  home: https://github.com/nschloe/pygalmesh/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: A Python frontend to CGAL’s 3D mesh generators.
  description: |
    pygalmesh is a Python frontend to CGAL’s 3D mesh generation capabilities. pygalmesh makes it easy to create high-quality 3D volume meshes, periodic volume meshes, and surface meshes. 
  doc_url: https://github.com/nschloe/pygalmesh
  dev_url: https://github.com/nschloe/pygalmesh

extra:
  recipe-maintainers:
    - nschloe
    - flothesof
